# Generated by Django 2.2.5 on 2020-02-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_animehouse_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animehouse',
            name='ano',
            field=models.IntegerField(default=2000),
        ),
    ]
