# Generated by Django 2.2.5 on 2019-10-24 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('avaliacao', models.IntegerField()),
                ('sinopse', models.CharField(max_length=200)),
                ('class_indicativa', models.IntegerField()),
                ('imagem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('sinopse', models.CharField(max_length=1000)),
                ('duracao', models.IntegerField()),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('F', 'Filler')], max_length=2)),
                ('data_criacao', models.DateTimeField(verbose_name='Data de criação')),
                ('data_adicao', models.DateTimeField(verbose_name='Data de Adição')),
                ('imagem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_genero', models.CharField(choices=[('acao', 'Ação'), ('comedia', 'Comédia'), ('aventura', 'Aventura'), ('sliceoflife', 'Slice of life'), ('romance', 'Romance')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tag', models.CharField(choices=[('violencia', 'violencia'), ('linguagem ofensiva', 'Linguagem Ofensiva'), ('ecchi', 'Ecchi')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Legenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=200)),
                ('caminho', models.CharField(max_length=200)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Episodio')),
            ],
        ),
        migrations.AddField(
            model_name='episodio',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddField(
            model_name='episodio',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Temporada'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=200)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Episodio')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='generos',
            field=models.ManyToManyField(to='main.Genero'),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
