# Generated by Django 2.2.5 on 2019-12-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191114_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='sinopse',
            field=models.CharField(max_length=2000),
        ),
    ]
